// Generated by https://quicktype.io

export interface ChampionList {
    type:    TypeElement[];
    format:  Format[];
    version: VersionElement[];
    results: SmallChampion[];
    ver:     string;
}

export interface Format {
    format: string;
}

export interface SmallChampion {
    version: VersionEnum;
    id:      string;
    key:     string;
    name:    string;
    title:   string;
    blurb:   string;
    img:     string;
    info:    Info;
    image:   Image;
    tags:    Tag[];
    partype: string;
    stats:   { [key: string]: number };
}

export interface Image {
    full:   string;
    sprite: Sprite;
    group:  TypeEnum;
    x:      number;
    y:      number;
    w:      number;
    h:      number;
}

export enum TypeEnum {
    Champion = "champion",
}

export enum Sprite {
    Champion0PNG = "champion0.png",
    Champion1PNG = "champion1.png",
    Champion2PNG = "champion2.png",
    Champion3PNG = "champion3.png",
    Champion4PNG = "champion4.png",
    Champion5PNG = "champion5.png",
}

export interface Info {
    attack:     number;
    defense:    number;
    magic:      number;
    difficulty: number;
}

export enum Tag {
    Assassin = "Assassin",
    Fighter = "Fighter",
    Mage = "Mage",
    Marksman = "Marksman",
    Support = "Support",
    Tank = "Tank",
}

export enum VersionEnum {
    The1261 = "12.6.1",
}

export interface TypeElement {
    type: TypeEnum;
}

export interface VersionElement {
    version: VersionEnum;
}
